/* eslint-disable */
// This file is auto-generated by scripts/generate-case-wizard-types.js
// Do not edit manually.

export const CASE_WIZARD_MESSAGES = {
  agNumber: 'Asigná un número de HC/AG',
  pacienteNombre: 'Ingresá el nombre del paciente',
  pacienteDni: 'Completá el DNI',
  motivoGroup: 'Seleccioná el grupo del motivo de consulta',
  motivoDetail: 'Elegí el motivo puntual dentro del grupo',
  motivoPaciente: 'Escribí el relato del paciente para orientar la consulta',
  enfInicioContexto: 'Describí el inicio y contexto del cuadro clínico',
  enfEvolucionActual: 'Contá la evolución reciente del cuadro',
  enfManifestacionesClaves: 'Detallá las manifestaciones principales del cuadro',
  consultaFecha: 'Indicá la fecha de la consulta',
} as const;

export type CaseWizardMessageKey = keyof typeof CASE_WIZARD_MESSAGES;

export const getCaseWizardMessage = (key: CaseWizardMessageKey) => CASE_WIZARD_MESSAGES[key];
